### ISSUE TITLE
Default linters included with EnableDefaultLinters set to false

### ISSUE THREAD

**Issue by mhoofman** [tleish/pronto-erb_lint#9]
Thanks for the gem - works great along with the gitlab formatters!

A project I'm running has an erblint configuration set to _not_ use any of the default linters using the configuration setting in `.erb-lint.yml`: `EnableDefaultLinters: false` without any other explicit configuration for default erblint linters.

Erb lint config example:

```
---
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**'
glob: "**/*.{html,text,js}{+*,}.erb"
EnableDefaultLinters: false
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
```

However, pronto with erblint appears to include these default linters. For example running with pronto will include default linters:

```
bundle exec pronto run --runner=erb_lint
```

Running with erblint honors the `erb-lint.yml` configuration and does not run the default linters:

```
bundler exec erblint
```

How can pronto honor the `.erb-lint.yml` to _not_ use the default linters from the `EnableDefaultLinters` setting?

**Update**
- Changed `erb-lint.yml` to `.erb-lint.yml`.
